# This source code is licensed under MIT license found in the
# LICENSE file in the root directory of this source tree.
# Author: Or Tal.

defaults:
  - data: dummy
  - model: dummy
  - training: dummy
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

seed: 2036

experiment_name: dummy # this defines the directory this experiment is saved into and all the corresponding logging
solver_name: base
train: True # if false, train_or_eval script will load best/last (depends on train config) and evaluate over the test set

# Weights and Biases
wandb_mode: disabled # TODO: set to online to log

# Hydra config
hydra:
  run:
    dir: ./outputs/${experiment_name}  # this specifies where the model outputs will be saved to
  job:
    config:
      # configuration for the ${hydra.job.override_dirname} runtime variable
      override_dirname:
        kv_sep: '='
        item_sep: ','
        # Remove all paths, as the / in them would mess up things
        # Remove params that would not impact the training itself
        # Remove all slurm and submit params.
        # This is ugly I know...
        exclude_keys: [
          'hydra.job_logging.handles.file.filename',
          'dset.train', 'dset.valid', 'dset.test', 'dset.noisy_json', 'dset.noisy_dir',
          'num_prints', 'continue_from', 'save_again',
          'device', 'num_workers', 'print_freq', 'restart', 'verbose',
          'log', 'ddp', 'ddp_backend', 'rendezvous_file', 'rank', 'world_size']
  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        mode: w
        formatter: colorlog
        filename: trainer.log
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr

  hydra_logging:
    handlers:
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr