# This source code is licensed under MIT license found in the
# LICENSE file in the root directory of this source tree.


defaults:
  - data: dummy
  - model: dummy
  - training: dummy
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

seed: 2036

# Weights and Biases
wandb_mode: disabled # TODO: set to online to log
wandb:
  mode: ${wandb_mode} # online/offline/disabled ;
  log: all # gradients/parameters/all/None
  log_freq: 5
  n_files_to_log: 5 # number of files to upload to wandb or -1 for all files
  wandb_entity: 'huji-dl-audio-lab' # TODO: fill entity name
  project: "fill name" # TODO: fill wandb project name

# Checkpointing, by default automatically load last checkpoint
checkpoint: true
continue_from: '' # Path the a checkpoint.th file to start from.
                  # this is not used in the name of the experiment!
                  # so use a dummy=something not to mixup experiments.
continue_best: False  # continue from best, not last state if continue_from is set.
continue_pretrained:   # use either dns48, dns64 or master64 to fine tune from pretrained-model
restart: false # Ignore existing checkpoints
checkpoint_file: checkpoint.th
best_file: best.th  # will contain only best model at any point
history_file: history.json
samples_dir: samples
save_again: false  # if true, only load checkpoint and save again, useful to reexport best.th

# Hydra config
hydra:
  run:
    dir: ./outputs/${experiment_name}  # this specifies where the model outputs will be saved to
  job:
    config:
      # configuration for the ${hydra.job.override_dirname} runtime variable
      override_dirname:
        kv_sep: '='
        item_sep: ','
        # Remove all paths, as the / in them would mess up things
        # Remove params that would not impact the training itself
        # Remove all slurm and submit params.
        # This is ugly I know...
        exclude_keys: [
          'hydra.job_logging.handles.file.filename',
          'dset.train', 'dset.valid', 'dset.test', 'dset.noisy_json', 'dset.noisy_dir',
          'num_prints', 'continue_from', 'save_again',
          'device', 'num_workers', 'print_freq', 'restart', 'verbose',
          'log', 'ddp', 'ddp_backend', 'rendezvous_file', 'rank', 'world_size']
  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        mode: w
        formatter: colorlog
        filename: trainer.log
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr

  hydra_logging:
    handlers:
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr